from dotenv import load_dotenv
import os

load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", default="YOUR_TELEGRAM_TOKEN_HERE")
UNSPLASH_CLIENT_ID = os.getenv("UNSPLASH_CLIENT_ID", default="YOUR_UNSPLASH_CLIENT_ID_HERE")
UNSPLASH_REGULAR_IMAGES_DIR = os.getenv("UNSPLASH_REGULAR_IMAGES_DIR", default="UNSPLASH_REGULAR_IMAGES_DIR_HERE")
UNSPLASH_SMALL_IMAGES_DIR = os.getenv("UNSPLASH_SMALL_IMAGES_DIR", default="UNSPLASH_SMALL_IMAGES_DIR_HERE")
TTS_GENERATIONS_DIR = os.getenv("TTS_GENERATIONS_DIR", default="TTS_GENERATIONS_DIR_HERE")
DB_URL = os.getenv("DB_URL", default="YOUR_DB_URI_HERE")
